#!/usr/bin/env python3
"""Generate src/savgol_coeffs.h — the exact scipy Savitzky-Golay kernels used
by stage 05, so the C port matches scipy.signal.savgol_filter bit-for-bit
(interior kernel + per-position edge kernels, mode='interp').

Run from firmware/dsp_port/ with the project venv:
    ../../.venv/Scripts/python.exe gen_savgol_coeffs.py
"""
from scipy.signal import savgol_coeffs

WIN, ORDER = 21, 3
half = WIN // 2

# use='dot' so the C code can dot the kernel directly against the samples in
# natural order (no convolution reversal). Interior kernel is symmetric so it
# is identical either way; edges differ, and 'dot' matches our C indexing:
#   leading  dst[i]      = sum_k EDGE[i][k]  * src[k]
#   trailing dst[n-1-pe] = sum_k EDGE[pe][k] * src[n-1-k]
interior = savgol_coeffs(WIN, ORDER, use='dot')               # centered
edges = [savgol_coeffs(WIN, ORDER, pos=p, use='dot') for p in range(half)]

def fmt(arr):
    return ", ".join(f"{v:.17e}f" for v in arr)

lines = []
lines.append("/* savgol_coeffs.h — GENERATED by gen_savgol_coeffs.py. Do not edit by hand.")
lines.append(f" * Savitzky-Golay window={WIN} order={ORDER}, matching scipy savgol_filter")
lines.append(" * (mode='interp'): interior uses SAVGOL_INTERIOR; the first `half` outputs")
lines.append(" * use SAVGOL_EDGE[pos] over the first WIN samples; the last `half` outputs")
lines.append(" * use the reversed edge kernels over the last WIN samples. */")
lines.append("#ifndef DSP_SAVGOL_COEFFS_H")
lines.append("#define DSP_SAVGOL_COEFFS_H")
lines.append(f"#define SAVGOL_WIN {WIN}")
lines.append(f"#define SAVGOL_HALF {half}")
lines.append(f"static const float SAVGOL_INTERIOR[SAVGOL_WIN] = {{ {fmt(interior)} }};")
lines.append(f"static const float SAVGOL_EDGE[SAVGOL_HALF][SAVGOL_WIN] = {{")
for p in range(half):
    lines.append(f"  {{ {fmt(edges[p])} }},")
lines.append("};")
lines.append("#endif")

open("src/savgol_coeffs.h","w").write("\n".join(lines)+"\n")
print("wrote src/savgol_coeffs.h")
