#!/usr/bin/env python3
"""Generate src/butter_coeffs.h — exact scipy Butterworth SOS + zi for stage 06
(order 4 bandpass 0.1-0.5 Hz at fs=10 Hz), so the C sosfiltfilt matches scipy.

    ../../.venv/Scripts/python.exe gen_butter_coeffs.py
"""
from scipy.signal import butter, sosfilt_zi

ORDER, LOW, HIGH, FS = 4, 0.1, 0.5, 10.0
nyq = 0.5 * FS
sos = butter(ORDER, [LOW / nyq, HIGH / nyq], btype='bandpass', output='sos')
zi = sosfilt_zi(sos)                 # (n_sections, 2)
ns = sos.shape[0]
padlen = 3 * (2 * ORDER + 1)

def row(a): return ", ".join(f"{v:.17e}f" for v in a)

L = []
L.append("/* butter_coeffs.h — GENERATED by gen_butter_coeffs.py. Do not edit.")
L.append(f" * Butterworth order={ORDER} bandpass {LOW}-{HIGH} Hz at fs={FS} Hz, SOS form,")
L.append(" * plus per-section steady-state zi for sosfiltfilt. */")
L.append("#ifndef DSP_BUTTER_COEFFS_H")
L.append("#define DSP_BUTTER_COEFFS_H")
L.append(f"#define BUTTER_NSECTIONS {ns}")
L.append(f"#define BUTTER_PADLEN {padlen}")
L.append(f"static const float BUTTER_SOS[BUTTER_NSECTIONS][6] = {{")
for r in sos:
    L.append(f"  {{ {row(r)} }},")
L.append("};")
L.append(f"static const float BUTTER_ZI[BUTTER_NSECTIONS][2] = {{")
for r in zi:
    L.append(f"  {{ {row(r)} }},")
L.append("};")
L.append("#endif")
open("src/butter_coeffs.h","w").write("\n".join(L)+"\n")
print("wrote src/butter_coeffs.h  (nsections=%d padlen=%d)" % (ns, padlen))
