/* config.example.h — copy to config.h and fill in. config.h is GITIGNORED
 * (may contain a WiFi password / device token = secrets). Never commit config.h.
 *
 * TWO WAYS TO PROVISION A DEVICE:
 *
 * 1. Production (recommended): leave the per-device fields below EMPTY ("").
 *    Flash this same generic firmware to every board. On first boot the device
 *    opens the "Wi-Health-Setup" hotspot; the caretaker enters WiFi + a short
 *    PAIRING CODE (generated by the admin panel). The device then fetches its
 *    device id + token + Firebase config from the backend and stores them in
 *    NVS. No per-device token, no reflashing.
 *
 * 2. Developer shortcut: fill CFG_DEVICE_ID / CFG_WEB_API_KEY / CFG_DB_URL /
 *    CFG_DEVICE_TOKEN below (mint the token via POST /admin/devices/<id>/token
 *    or backend/scripts/print-device-token.mjs). On first boot these seed NVS
 *    and the device skips the pairing step — the old behaviour.
 */
#ifndef UPLOADER_CONFIG_H
#define UPLOADER_CONFIG_H

/* --- WiFi (2.4 GHz; the rig auto-discovers the channel, so any channel works) ---
 * Developer SEED: if CFG_WIFI_SSID is set, the uploader joins it on first boot
 * and saves to NVS. Leave EMPTY ("") to start SoftAP captive-portal setup so an
 * end user enters their own WiFi (+ pairing code) with no reflashing. */
#define CFG_WIFI_SSID    ""
#define CFG_WIFI_PASS    ""

/* --- Backend (SAME for every device; needed for the pairing-code claim) ---
 * The base URL of the Wi-Health backend, e.g. the Railway deployment. The
 * device POSTs its pairing code to <CFG_BACKEND_URL>/devices/claim-code. */
#define CFG_BACKEND_URL  "https://your-backend.up.railway.app"

/* --- Per-device Firebase identity (PRODUCTION: leave EMPTY, provisioned via
 * the pairing code). Fill only for the developer shortcut described above. --- */
#define CFG_DEVICE_ID    ""      /* e.g. "test-device-1" */
#define CFG_WEB_API_KEY  ""      /* Firebase web API key */
#define CFG_DB_URL       ""      /* e.g. https://<proj>-default-rtdb.<region>.firebasedatabase.app */
#define CFG_DEVICE_TOKEN ""      /* long custom token; first-boot only */

#endif /* UPLOADER_CONFIG_H */
