#!/usr/bin/env python3
"""Generate main/test_data.h — the embedded golden vectors the on-device
self-test runs through the C DSP chain, plus the expected estimator output.
Kept small (flash const) so it fits comfortably on the ESP32-S3.

    ../../.venv/Scripts/python.exe gen_testdata.py
"""
from pathlib import Path

VEC = Path("../dsp_port/test_vectors")

def load_vec(name):
    with (VEC / name).open() as f:
        n = int(f.readline())
        return [float(x) for x in f.read().split()]

def load_kv(name):
    d = {}
    for line in (VEC / name).read_text().splitlines():
        if line.startswith("#") or not line.strip():
            continue
        k, v = line.split()[:2]
        d[k] = v
    return d

bandpass = load_vec("06_bandpass.txt")
est = load_kv("07_estimator.txt")

L = []
L.append("/* test_data.h — GENERATED by gen_testdata.py. Embedded golden vectors")
L.append(" * for the on-device DSP self-test. Do not edit by hand. */")
L.append("#ifndef DSP_SELFTEST_TEST_DATA_H")
L.append("#define DSP_SELFTEST_TEST_DATA_H")
L.append("")
L.append(f"#define TD_BANDPASS_N {len(bandpass)}")
L.append("/* stage-06 bandpass waveform (estimator input) */")
L.append("static const float TD_BANDPASS[TD_BANDPASS_N] = {")
for i in range(0, len(bandpass), 8):
    chunk = bandpass[i:i+8]
    L.append("  " + ", ".join(f"{v:.9g}f" for v in chunk) + ",")
L.append("};")
L.append("")
L.append("/* expected estimator outputs (Python golden) */")
L.append(f"#define TD_EXP_BPM_FFT     {est['bpm_fft']}f")
L.append(f"#define TD_EXP_BPM_AC      {est['bpm_ac']}f")
L.append(f"#define TD_EXP_BPM_MEDIAN  {est['bpm_median']}f")
L.append(f"#define TD_EXP_CONFIDENCE  {est['confidence']}f")
L.append(f'#define TD_EXP_STATUS      "{est["status"]}"')
L.append("")
L.append("#endif")
Path("main/test_data.h").write_text("\n".join(L) + "\n")
print(f"wrote main/test_data.h  (bandpass N={len(bandpass)}, ~{len(bandpass)*4} bytes flash)")
