#!/usr/bin/env python3
"""Generate main/test_data.h — embedded golden vectors for the on-device DSP
self-test. Two test paths:

  (A) estimator-only: the stage-06 bandpass waveform -> dsp_estimate.
  (B) per-window chain: the stage-02 resample window + PRE-SELECTED pairs ->
      stages 04(CSCR) -> 05(waveform) -> 06(bandpass) -> 07(estimator).
      Stage 03 (pair selection) is NOT run on-device — it is far too slow
      per-window (3000 candidate DFTs); it runs once at session start and the
      pairs are cached. Here we embed the golden pairs to stand in for that.

The resample window (440x108 complex f32 ~ 371 KB) lives in FLASH as a const,
not RAM.

    ../../.venv/Scripts/python.exe gen_testdata.py
"""
from pathlib import Path

VEC = Path("../dsp_port/test_vectors")

def load_rvec(name):
    with (VEC / name).open() as f:
        int(f.readline()); return [float(x) for x in f.read().split()]

def load_complex(name):
    with (VEC / name).open() as f:
        n, s = map(int, f.readline().split())
        vals = [float(x) for x in f.read().split()]
    return n, s, vals   # vals interleaved re,im, length n*s*2

def load_pairs(name):
    with (VEC / name).open() as f:
        p = int(f.readline())
        ij = [tuple(map(int, line.split())) for line in f.read().splitlines() if line.strip()]
    return p, ij

def load_kv(name):
    d = {}
    for line in (VEC / name).read_text().splitlines():
        if line.startswith("#") or not line.strip(): continue
        k, v = line.split()[:2]; d[k] = v
    return d

bandpass = load_rvec("06_bandpass.txt")
est = load_kv("07_estimator.txt")
rn, rs, rvals = load_complex("02_resample.txt")
pp, pairs = load_pairs("03_pairs.txt")

def cfloat(v):
    """Format a float as a valid C float literal. %g drops the decimal point
    for whole numbers ("-20"), which C then reads as an int and rejects the
    'f' suffix — so ensure a '.' or exponent is always present before 'f'."""
    s = f"{v:.9g}"
    if "." not in s and "e" not in s and "E" not in s and "n" not in s:  # nan/inf guard
        s += ".0"
    return s + "f"

def emit_float_array(L, name, vals, per=8):
    L.append(f"static const float {name}[] = {{")
    for i in range(0, len(vals), per):
        L.append("  " + ", ".join(cfloat(v) for v in vals[i:i+per]) + ",")
    L.append("};")

L = []
L.append("/* test_data.h — GENERATED by gen_testdata.py. Do not edit. */")
L.append("#ifndef DSP_SELFTEST_TEST_DATA_H")
L.append("#define DSP_SELFTEST_TEST_DATA_H")
L.append("")
# --- estimator-only path ---
L.append(f"#define TD_BANDPASS_N {len(bandpass)}")
emit_float_array(L, "TD_BANDPASS", bandpass)
L.append("")
# --- per-window chain path ---
L.append(f"#define TD_RESAMPLE_N {rn}")
L.append(f"#define TD_RESAMPLE_S {rs}")
emit_float_array(L, "TD_RESAMPLE", rvals)   # interleaved re,im, n*s*2
L.append("")
L.append(f"#define TD_PAIRS_P {pp}")
L.append("static const int TD_PAIRS_I[] = {" + ", ".join(str(i) for i,_ in pairs) + "};")
L.append("static const int TD_PAIRS_J[] = {" + ", ".join(str(j) for _,j in pairs) + "};")
L.append("")
# --- expected outputs (cfloat-formatted so whole numbers keep a decimal) ---
L.append(f"#define TD_EXP_BPM_FFT     {cfloat(float(est['bpm_fft']))}")
L.append(f"#define TD_EXP_BPM_AC      {cfloat(float(est['bpm_ac']))}")
L.append(f"#define TD_EXP_BPM_MEDIAN  {cfloat(float(est['bpm_median']))}")
L.append(f"#define TD_EXP_CONFIDENCE  {cfloat(float(est['confidence']))}")
L.append(f'#define TD_EXP_STATUS      "{est["status"]}"')
L.append("")
L.append("#endif")
Path("main/test_data.h").write_text("\n".join(L) + "\n")
kb = (len(bandpass) + len(rvals)) * 4 / 1024
print(f"wrote main/test_data.h  (~{kb:.0f} KB flash const: bandpass {len(bandpass)}, resample {rn}x{rs}, pairs {pp})")
