/// Build-time switches for the app.
class AppConfig {
  AppConfig._();

  /// Master switch between the mock backend and real Firebase.
  ///
  /// Off by default (mock auth + mock data — tests rely on this).
  /// Turn on per-run with a dart-define, no code edit needed:
  ///
  ///   flutter run --dart-define=USE_FIREBASE=true
  ///
  /// Requires lib/firebase_options.dart generated by `flutterfire
  /// configure` and the cloud/database.rules.json rules deployed.
  static const bool useFirebase =
      bool.fromEnvironment('USE_FIREBASE', defaultValue: false);
}
